-- Truncate existing data to prevent primary key collisions on re-runs
TRUNCATE TABLE public.campsites CASCADE;
TRUNCATE TABLE public.events CASCADE;

-- Insert Campsites
INSERT INTO public.campsites (id, title, location, price, rating, reviews_count, terrain, tags, image_url, description, amenities) VALUES
('c1', 'Camp Roxx', 'Kangojodi, Himachal Pradesh', 2200, 4.8, 248, 'Forest', ARRAY['Forest', 'Adventure', 'Zip-lining'], 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=800&q=80', 'Nestled inside a private 1,700-acre pine forest near Nahan. Features alpine cabin tents, nature trails, rock climbing, and zip-lining over pure mountain streams.', ARRAY['Cabin Tents', 'Running Water', 'First Aid', 'Adventure Sports', 'Bonfire Pit']),
('c2', 'Winds Desert Camp', 'Sam Sand Dunes, Jaisalmer', 4500, 4.9, 312, 'Desert', ARRAY['Desert', 'Cultural Show', 'Camel Safari'], 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80', 'Experience royal Rajasthani hospitality at Kanoi near Sam Sand Dunes. Luxury Swiss tents with attached bathrooms, camel safaris, and evening folk performances under Thar''s starry skies.', ARRAY['Attached Bath', 'Swiss Luxury Tents', 'Rajasthani Buffet', 'Cultural Show', 'Stargazing']),
('c3', 'Pawna Lake Camping', 'Thakursai, Lonavala', 1500, 4.7, 512, 'Lakeside', ARRAY['Lakeside', 'Bonfire & DJ', 'Kayaking'], 'https://images.unsplash.com/photo-1537905569824-f89f14cceb68?auto=format&fit=crop&w=800&q=80', 'Relax by the calm waters of Pawna Lake in Thakursai. Offers dome tents, delicious local Maharashtrian barbecue, acoustic music nights, and scenic views of Tikona Fort.', ARRAY['Lakeside Tents', 'Barbecue', 'DJ Night', 'Toilets', 'Charging Points']),
('c4', 'Shivpuri Riverside Camp', 'Shivpuri, Rishikesh', 1800, 4.8, 420, 'Riverside', ARRAY['Riverside', 'Rafting', 'Bonfire'], 'https://images.unsplash.com/photo-1496080174650-637e3f22fa03?auto=format&fit=crop&w=800&q=80', 'Located on the sandy banks of the Ganges in Shivpuri. Wake up to the roar of river rapids, enjoy beach volleyball, and set off on world-class white water rafting expeditions.', ARRAY['Dome Tents', 'Rafting Access', 'Volleyball Court', 'First Aid', 'Clean Washrooms']);

-- Insert Events
INSERT INTO public.events (id, title, location, date, price, guide, guide_title, capacity, availability, status, image_url, description) VALUES
('e1', 'Monsoon Trek & Camp', 'Harishchandragad, MH', 'July 15-16, 2026', 2200, 'Sameer Joshi', 'Western Ghats Specialist', '25 Campers', '8 Slots Left', 'Upcoming', 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=800&q=80', 'Experience the monsoon beauty of Harishchandragad fort, camp above the clouds, and view the iconic Kokankada cliff.'),
('e2', 'High Altitude Expedition', 'Hampta Pass, HP', 'Aug 10-15, 2026', 9500, 'Aryan Negi', 'Himalayan Guide', '15 Campers', '4 Slots Left', 'Upcoming', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'Cross the lush green valleys of Kullu to the stark high-altitude deserts of Spiti Valley over the glorious Hampta Pass.'),
('e3', 'Beach Trek & Stargazing', 'Gokarna, Karnataka', 'Sept 04-06, 2026', 4500, 'Priya Nair', 'Coastal Trek Leader', '30 Campers', '12 Slots Left', 'Upcoming', 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80', 'A weekend coastal beach trek covering Om Beach, Half Moon Beach, and Paradise Beach, topped with astronomical stargazing sessions.');
